-- Active: 1761302252785@@@443@SCOTT
INSERT INTO HISTORY (EMPNO, DATE_REF, VALEUR, ID_RUBRIQUE)
SELECT EMPNO, NULL, SAL, 1
FROM EMP;

SELECT DATE_REF FROM HISTORY WHERE EMPNO = 7369 AND DATE_REF IS NULL;

SELECT sal + avantages AS total_gain FROM EMP WHERE EMPNO = 7369